ecommerce_platform:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: ecommerce-data-platform-492602     # replace with your actual project ID
      dataset: staging
      keyfile: /usr/local/airflow/include/gcp-credentials.json
      location: asia-southeast1
      threads: 4
      timeout_seconds: 300
    local:
      type: bigquery
      method: service-account
      project: ecommerce-data-platform-492602
      dataset: staging
      keyfile: c:\Users\hungv\ecommerce-data-platform\gcp-credentials.json
      location: asia-southeast1
      threads: 4
      timeout_seconds: 300